name: Build static files to pages branch
on:
  push:
    branches: [master]

jobs:
  build:
    permisssions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Build static files
      uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: bun run build

    - name: Init a new repo in dist folder and commite generated files
      run: |
        cd dist/
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git commit -a -m 'build'

    - name: Force push to pages branch
      uses: ad-m/github-push-action@v0.8.0
      with:
        branch: pages
        force: true
        directory: ./dist
