name: Build static files to pages branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build static files
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm ci
    - run: npm run build

    - name: Init a new repo in dist folder and commite generated files
      run: |
        cd dist/
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git commit -m 'build'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: pages
        force: true
        directory: ./dist
